#!/usr/bin/env bash
# Resolve every image in versions.env to an immutable digest.
#
# Tags move; digests do not. Requirement M-3 says a run is only a result if the
# exact image bytes are recorded, so this lock is what makes a published number
# traceable months later.
#
# Usage:
#   scripts/resolve-digests.sh          # rewrite images.lock
#   scripts/resolve-digests.sh --check  # fail if the lock is stale (for CI)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VERSIONS_FILE="${REPO_ROOT}/infra/compose/versions.env"
LOCK_FILE="${REPO_ROOT}/infra/compose/images.lock"

CHECK_ONLY=0
[[ "${1:-}" == "--check" ]] && CHECK_ONLY=1

# shellcheck disable=SC1090
set -a; source "${VERSIONS_FILE}"; set +a

IMAGES=(
  "${KAFKA_IMAGE}:${KAFKA_VERSION}"
  "${PULSAR_IMAGE}:${PULSAR_VERSION}"
  "${ICEBERG_REST_IMAGE}:${ICEBERG_REST_VERSION}"
  "${MINIO_IMAGE}:${MINIO_VERSION}"
  "${MC_IMAGE}:${MC_VERSION}"
  "${FLINK_IMAGE}:${FLINK_VERSION}"
  "${SPARK_IMAGE}:${SPARK_VERSION}"
  "${AIRFLOW_IMAGE}:${AIRFLOW_VERSION}"
  "${POSTGRES_IMAGE}:${POSTGRES_VERSION}"
)

resolve() {
  # Print the multi-arch index digest for an image reference.
  docker buildx imagetools inspect "$1" 2>/dev/null \
    | awk '/^Digest:/ { print $2; exit }'
}

TMP="$(mktemp)"
trap 'rm -f "${TMP}"' EXIT

{
  echo "# Resolved image digests. Generated by scripts/resolve-digests.sh."
  echo "#"
  echo "# Tags are mutable; digests are not. A benchmark run records these so that a"
  echo "# result can always be traced to the exact bytes that produced it (M-3)."
  echo "#"
  echo "# Do not hand-edit. Regenerate after any change to versions.env, and treat an"
  echo "# unexpected digest change on an unchanged tag as a reason to re-baseline"
  echo "# rather than to compare across it."
  echo "#"
  echo "# resolved: $(date -u +%Y-%m-%d)"
  echo
} > "${TMP}"

failed=0
for img in "${IMAGES[@]}"; do
  digest="$(resolve "${img}")"
  if [[ -z "${digest}" ]]; then
    echo "ERROR: could not resolve ${img}" >&2
    failed=1
    continue
  fi
  printf '%s %s\n' "${img}" "${digest}" >> "${TMP}"
done
[[ "${failed}" -eq 0 ]] || exit 1

if [[ "${CHECK_ONLY}" -eq 1 ]]; then
  # Compare only the image lines; the resolved-on date is expected to differ.
  if diff <(grep -v '^#' "${LOCK_FILE}" | grep -v '^$') \
          <(grep -v '^#' "${TMP}"       | grep -v '^$') >/dev/null; then
    echo "images.lock is up to date"
  else
    echo "ERROR: images.lock is stale. Run scripts/resolve-digests.sh" >&2
    diff <(grep -v '^#' "${LOCK_FILE}") <(grep -v '^#' "${TMP}") || true
    exit 1
  fi
else
  mv "${TMP}" "${LOCK_FILE}"
  trap - EXIT
  echo "wrote ${LOCK_FILE}"
fi
